.class public final Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;
.super Ljava/lang/Object;
.source "VirgilPythiaClient.java"

# interfaces
.implements Lcom/virgilsecurity/pythia/client/PythiaClient;


# static fields
.field private static final BASE_URL:Ljava/lang/String; = "https://api.virgilsecurity.com"

.field private static final LOGGER:Ljava/util/logging/Logger;

.field private static final VIRGIL_AGENT_HEADER:Ljava/lang/String; = "virgil-agent"


# instance fields
.field private baseUrl:Ljava/net/URL;

.field private bppVirgilAgent:Ljava/lang/String;

.field private brainkeyVirgilAgent:Ljava/lang/String;


# direct methods
.method static constructor <clinit>()V
    .locals 1

    .line 67
    const-class v0, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;

    invoke-virtual {v0}, Ljava/lang/Class;->getName()Ljava/lang/String;

    move-result-object v0

    invoke-static {v0}, Ljava/util/logging/Logger;->getLogger(Ljava/lang/String;)Ljava/util/logging/Logger;

    move-result-object v0

    sput-object v0, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;->LOGGER:Ljava/util/logging/Logger;

    return-void
.end method

.method public constructor <init>()V
    .locals 1

    .line 80
    const-string v0, "https://api.virgilsecurity.com"

    invoke-direct {p0, v0}, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;-><init>(Ljava/lang/String;)V

    .line 81
    return-void
.end method

.method public constructor <init>(Ljava/lang/String;)V
    .locals 3
    .param p1, "baseUrl"    # Ljava/lang/String;

    .line 89
    const-string v0, "bpp"

    const-string v1, "brainkey"

    const-string v2, "0.3.7"

    invoke-direct {p0, p1, v0, v1, v2}, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;-><init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V

    .line 90
    return-void
.end method

.method public constructor <init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
    .locals 1
    .param p1, "bppProduct"    # Ljava/lang/String;
    .param p2, "brainkeyProduct"    # Ljava/lang/String;
    .param p3, "version"    # Ljava/lang/String;

    .line 100
    const-string v0, "https://api.virgilsecurity.com"

    invoke-direct {p0, v0, p1, p2, p3}, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;-><init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V

    .line 101
    return-void
.end method

.method public constructor <init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
    .locals 4
    .param p1, "baseUrl"    # Ljava/lang/String;
    .param p2, "bppProduct"    # Ljava/lang/String;
    .param p3, "brainkeyProduct"    # Ljava/lang/String;
    .param p4, "version"    # Ljava/lang/String;

    .line 112
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 113
    const-string v0, "VirgilPythiaClient -> \'baseUrl\' should not be null"

    invoke-static {p1, v0}, Lcom/virgilsecurity/common/util/Validator;->checkNullAgrument(Ljava/lang/Object;Ljava/lang/String;)V

    .line 115
    :try_start_0
    new-instance v0, Ljava/net/URL;

    invoke-direct {v0, p1}, Ljava/net/URL;-><init>(Ljava/lang/String;)V

    iput-object v0, p0, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;->baseUrl:Ljava/net/URL;
    :try_end_0
    .catch Ljava/net/MalformedURLException; {:try_start_0 .. :try_end_0} :catch_0

    .line 119
    nop

    .line 120
    invoke-direct {p0, p2, p3, p4}, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;->buildVirgilAgent(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V

    .line 121
    return-void

    .line 116
    :catch_0
    move-exception v0

    .line 117
    .local v0, "e":Ljava/net/MalformedURLException;
    sget-object v1, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;->LOGGER:Ljava/util/logging/Logger;

    sget-object v2, Ljava/util/logging/Level;->SEVERE:Ljava/util/logging/Level;

    const-string v3, "Base URL has wrong format"

    invoke-virtual {v1, v2, v3, v0}, Ljava/util/logging/Logger;->log(Ljava/util/logging/Level;Ljava/lang/String;Ljava/lang/Throwable;)V

    .line 118
    new-instance v1, Ljava/lang/IllegalArgumentException;

    const-string v2, "VirgilPythiaClient -> \'baseUrl\' has wrong format"

    invoke-direct {v1, v2}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    throw v1
.end method

.method private buildVirgilAgent(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
    .locals 9
    .param p1, "bppProduct"    # Ljava/lang/String;
    .param p2, "brainkeyProduct"    # Ljava/lang/String;
    .param p3, "version"    # Ljava/lang/String;

    .line 245
    invoke-static {}, Lcom/virgilsecurity/sdk/utils/OsUtils;->getOsAgentName()Ljava/lang/String;

    move-result-object v0

    .line 246
    .local v0, "osName":Ljava/lang/String;
    const/4 v1, 0x4

    new-array v2, v1, [Ljava/lang/Object;

    const/4 v3, 0x0

    aput-object p1, v2, v3

    const/4 v4, 0x1

    const-string v5, "jvm"

    aput-object v5, v2, v4

    const/4 v6, 0x2

    aput-object v0, v2, v6

    const/4 v7, 0x3

    aput-object p3, v2, v7

    const-string v8, "%1$s;%2$s;%3$s;%4$s"

    invoke-static {v8, v2}, Ljava/lang/String;->format(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;

    move-result-object v2

    iput-object v2, p0, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;->bppVirgilAgent:Ljava/lang/String;

    .line 248
    new-array v1, v1, [Ljava/lang/Object;

    aput-object p2, v1, v3

    aput-object v5, v1, v4

    aput-object v0, v1, v6

    aput-object p3, v1, v7

    invoke-static {v8, v1}, Ljava/lang/String;->format(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;

    move-result-object v1

    iput-object v1, p0, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;->brainkeyVirgilAgent:Ljava/lang/String;

    .line 250
    return-void
.end method

.method private createConnection(Ljava/lang/String;Ljava/lang/String;)Ljava/net/HttpURLConnection;
    .locals 4
    .param p1, "spec"    # Ljava/lang/String;
    .param p2, "token"    # Ljava/lang/String;
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    .line 185
    new-instance v0, Ljava/net/URL;

    iget-object v1, p0, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;->baseUrl:Ljava/net/URL;

    invoke-direct {v0, v1, p1}, Ljava/net/URL;-><init>(Ljava/net/URL;Ljava/lang/String;)V

    .line 186
    .local v0, "url":Ljava/net/URL;
    invoke-virtual {v0}, Ljava/net/URL;->openConnection()Ljava/net/URLConnection;

    move-result-object v1

    check-cast v1, Ljava/net/HttpURLConnection;

    .line 187
    .local v1, "urlConnection":Ljava/net/HttpURLConnection;
    const-string v2, "POST"

    invoke-virtual {v1, v2}, Ljava/net/HttpURLConnection;->setRequestMethod(Ljava/lang/String;)V

    .line 188
    const/4 v2, 0x1

    invoke-virtual {v1, v2}, Ljava/net/HttpURLConnection;->setDoOutput(Z)V

    .line 189
    const/4 v2, 0x0

    invoke-virtual {v1, v2}, Ljava/net/HttpURLConnection;->setUseCaches(Z)V

    .line 190
    const-string v2, "Content-Type"

    const-string v3, "application/json; charset=utf-8"

    invoke-virtual {v1, v2, v3}, Ljava/net/HttpURLConnection;->setRequestProperty(Ljava/lang/String;Ljava/lang/String;)V

    .line 193
    invoke-static {p2}, Lcom/virgilsecurity/sdk/utils/StringUtils;->isBlank(Ljava/lang/CharSequence;)Z

    move-result v2

    if-nez v2, :cond_0

    .line 194
    new-instance v2, Ljava/lang/StringBuilder;

    invoke-direct {v2}, Ljava/lang/StringBuilder;-><init>()V

    const-string v3, "Virgil "

    invoke-virtual {v2, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v2

    invoke-virtual {v2, p2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v2

    invoke-virtual {v2}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v2

    const-string v3, "Authorization"

    invoke-virtual {v1, v3, v2}, Ljava/net/HttpURLConnection;->setRequestProperty(Ljava/lang/String;Ljava/lang/String;)V

    goto :goto_0

    .line 196
    :cond_0
    sget-object v2, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;->LOGGER:Ljava/util/logging/Logger;

    const-string v3, "Provided token is blank"

    invoke-virtual {v2, v3}, Ljava/util/logging/Logger;->warning(Ljava/lang/String;)V

    .line 199
    :goto_0
    return-object v1
.end method

.method private execute(Ljava/net/HttpURLConnection;Ljava/lang/Object;Ljava/lang/Class;)Ljava/lang/Object;
    .locals 9
    .param p1, "urlConnection"    # Ljava/net/HttpURLConnection;
    .param p2, "requestBody"    # Ljava/lang/Object;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "<T:",
            "Ljava/lang/Object;",
            ">(",
            "Ljava/net/HttpURLConnection;",
            "Ljava/lang/Object;",
            "Ljava/lang/Class<",
            "TT;>;)TT;"
        }
    .end annotation

    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;,
            Lcom/virgilsecurity/pythia/model/exception/VirgilPythiaServiceException;
        }
    .end annotation

    .line 204
    .local p3, "clazz":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
    const-string v0, "Disconnecting..."

    invoke-static {p2}, Lcom/virgilsecurity/sdk/utils/ConvertionUtils;->serializeToJson(Ljava/lang/Object;)Ljava/lang/String;

    move-result-object v1

    .line 207
    .local v1, "body":Ljava/lang/String;
    :try_start_0
    invoke-virtual {p1}, Ljava/net/HttpURLConnection;->getOutputStream()Ljava/io/OutputStream;

    move-result-object v2

    invoke-static {v1}, Lcom/virgilsecurity/sdk/utils/ConvertionUtils;->toBytes(Ljava/lang/String;)[B

    move-result-object v3

    invoke-virtual {v2, v3}, Ljava/io/OutputStream;->write([B)V

    .line 209
    invoke-virtual {p1}, Ljava/net/HttpURLConnection;->getResponseCode()I

    move-result v2

    const/16 v3, 0x190

    if-lt v2, v3, :cond_2

    .line 210
    sget-object v2, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;->LOGGER:Ljava/util/logging/Logger;

    const-string v3, "Http error occurred..."

    invoke-virtual {v2, v3}, Ljava/util/logging/Logger;->warning(Ljava/lang/String;)V

    .line 211
    new-instance v3, Lcom/virgilsecurity/sdk/common/HttpError;

    invoke-virtual {p1}, Ljava/net/HttpURLConnection;->getResponseCode()I

    move-result v4

    .line 212
    invoke-virtual {p1}, Ljava/net/HttpURLConnection;->getResponseMessage()Ljava/lang/String;

    move-result-object v5

    invoke-direct {v3, v4, v5}, Lcom/virgilsecurity/sdk/common/HttpError;-><init>(ILjava/lang/String;)V

    .line 215
    .local v3, "httpError":Lcom/virgilsecurity/sdk/common/HttpError;
    new-instance v4, Ljava/io/BufferedInputStream;

    invoke-virtual {p1}, Ljava/net/HttpURLConnection;->getErrorStream()Ljava/io/InputStream;

    move-result-object v5

    invoke-direct {v4, v5}, Ljava/io/BufferedInputStream;-><init>(Ljava/io/InputStream;)V
    :try_end_0
    .catchall {:try_start_0 .. :try_end_0} :catchall_6

    .line 216
    .local v4, "in":Ljava/io/InputStream;
    :try_start_1
    const-string v5, "Trying to get error info..."

    invoke-virtual {v2, v5}, Ljava/util/logging/Logger;->fine(Ljava/lang/String;)V

    .line 217
    invoke-static {v4}, Lcom/virgilsecurity/sdk/utils/ConvertionUtils;->toString(Ljava/io/InputStream;)Ljava/lang/String;

    move-result-object v2

    .line 218
    .local v2, "errBody":Ljava/lang/String;
    invoke-static {v2}, Lcom/virgilsecurity/sdk/utils/StringUtils;->isBlank(Ljava/lang/CharSequence;)Z

    move-result v5

    if-nez v5, :cond_1

    .line 221
    invoke-static {}, Lcom/virgilsecurity/sdk/utils/ConvertionUtils;->getGson()Lcom/google/gson/Gson;

    move-result-object v5

    const-class v6, Lcom/virgilsecurity/sdk/common/ErrorResponse;

    invoke-virtual {v5, v2, v6}, Lcom/google/gson/Gson;->fromJson(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;

    move-result-object v5

    check-cast v5, Lcom/virgilsecurity/sdk/common/ErrorResponse;

    .line 222
    .local v5, "error":Lcom/virgilsecurity/sdk/common/ErrorResponse;
    invoke-virtual {v5}, Lcom/virgilsecurity/sdk/common/ErrorResponse;->getCode()I

    move-result v6

    const v7, 0xea67

    if-ne v6, v7, :cond_0

    .line 223
    new-instance v6, Lcom/virgilsecurity/pythia/model/exception/ThrottlingException;

    invoke-virtual {v5}, Lcom/virgilsecurity/sdk/common/ErrorResponse;->getCode()I

    move-result v7

    invoke-virtual {v5}, Lcom/virgilsecurity/sdk/common/ErrorResponse;->getMessage()Ljava/lang/String;

    move-result-object v8

    invoke-direct {v6, v7, v8, v3}, Lcom/virgilsecurity/pythia/model/exception/ThrottlingException;-><init>(ILjava/lang/String;Lcom/virgilsecurity/sdk/common/HttpError;)V

    .end local v1    # "body":Ljava/lang/String;
    .end local v3    # "httpError":Lcom/virgilsecurity/sdk/common/HttpError;
    .end local v4    # "in":Ljava/io/InputStream;
    .end local p1    # "urlConnection":Ljava/net/HttpURLConnection;
    .end local p2    # "requestBody":Ljava/lang/Object;
    .end local p3    # "clazz":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
    throw v6

    .line 225
    .restart local v1    # "body":Ljava/lang/String;
    .restart local v3    # "httpError":Lcom/virgilsecurity/sdk/common/HttpError;
    .restart local v4    # "in":Ljava/io/InputStream;
    .restart local p1    # "urlConnection":Ljava/net/HttpURLConnection;
    .restart local p2    # "requestBody":Ljava/lang/Object;
    .restart local p3    # "clazz":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
    :cond_0
    new-instance v6, Lcom/virgilsecurity/pythia/model/exception/VirgilPythiaServiceException;

    invoke-virtual {v5}, Lcom/virgilsecurity/sdk/common/ErrorResponse;->getCode()I

    move-result v7

    invoke-virtual {v5}, Lcom/virgilsecurity/sdk/common/ErrorResponse;->getMessage()Ljava/lang/String;

    move-result-object v8

    invoke-direct {v6, v7, v8, v3}, Lcom/virgilsecurity/pythia/model/exception/VirgilPythiaServiceException;-><init>(ILjava/lang/String;Lcom/virgilsecurity/sdk/common/HttpError;)V

    .end local v1    # "body":Ljava/lang/String;
    .end local v3    # "httpError":Lcom/virgilsecurity/sdk/common/HttpError;
    .end local v4    # "in":Ljava/io/InputStream;
    .end local p1    # "urlConnection":Ljava/net/HttpURLConnection;
    .end local p2    # "requestBody":Ljava/lang/Object;
    .end local p3    # "clazz":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
    throw v6

    .line 219
    .end local v5    # "error":Lcom/virgilsecurity/sdk/common/ErrorResponse;
    .restart local v1    # "body":Ljava/lang/String;
    .restart local v3    # "httpError":Lcom/virgilsecurity/sdk/common/HttpError;
    .restart local v4    # "in":Ljava/io/InputStream;
    .restart local p1    # "urlConnection":Ljava/net/HttpURLConnection;
    .restart local p2    # "requestBody":Ljava/lang/Object;
    .restart local p3    # "clazz":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
    :cond_1
    new-instance v5, Lcom/virgilsecurity/pythia/model/exception/VirgilPythiaServiceException;

    invoke-direct {v5, v3}, Lcom/virgilsecurity/pythia/model/exception/VirgilPythiaServiceException;-><init>(Lcom/virgilsecurity/sdk/common/HttpError;)V

    .end local v1    # "body":Ljava/lang/String;
    .end local v3    # "httpError":Lcom/virgilsecurity/sdk/common/HttpError;
    .end local v4    # "in":Ljava/io/InputStream;
    .end local p1    # "urlConnection":Ljava/net/HttpURLConnection;
    .end local p2    # "requestBody":Ljava/lang/Object;
    .end local p3    # "clazz":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
    throw v5
    :try_end_1
    .catchall {:try_start_1 .. :try_end_1} :catchall_0

    .line 215
    .end local v2    # "errBody":Ljava/lang/String;
    .restart local v1    # "body":Ljava/lang/String;
    .restart local v3    # "httpError":Lcom/virgilsecurity/sdk/common/HttpError;
    .restart local v4    # "in":Ljava/io/InputStream;
    .restart local p1    # "urlConnection":Ljava/net/HttpURLConnection;
    .restart local p2    # "requestBody":Ljava/lang/Object;
    .restart local p3    # "clazz":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
    :catchall_0
    move-exception v2

    .end local v1    # "body":Ljava/lang/String;
    .end local v3    # "httpError":Lcom/virgilsecurity/sdk/common/HttpError;
    .end local v4    # "in":Ljava/io/InputStream;
    .end local p1    # "urlConnection":Ljava/net/HttpURLConnection;
    .end local p2    # "requestBody":Ljava/lang/Object;
    .end local p3    # "clazz":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
    :try_start_2
    throw v2
    :try_end_2
    .catchall {:try_start_2 .. :try_end_2} :catchall_1

    .line 229
    .restart local v1    # "body":Ljava/lang/String;
    .restart local v3    # "httpError":Lcom/virgilsecurity/sdk/common/HttpError;
    .restart local v4    # "in":Ljava/io/InputStream;
    .restart local p1    # "urlConnection":Ljava/net/HttpURLConnection;
    .restart local p2    # "requestBody":Ljava/lang/Object;
    .restart local p3    # "clazz":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
    :catchall_1
    move-exception v5

    :try_start_3
    invoke-virtual {v4}, Ljava/io/InputStream;->close()V
    :try_end_3
    .catchall {:try_start_3 .. :try_end_3} :catchall_2

    goto :goto_0

    :catchall_2
    move-exception v6

    :try_start_4
    invoke-virtual {v2, v6}, Ljava/lang/Throwable;->addSuppressed(Ljava/lang/Throwable;)V

    .end local v1    # "body":Ljava/lang/String;
    .end local p1    # "urlConnection":Ljava/net/HttpURLConnection;
    .end local p2    # "requestBody":Ljava/lang/Object;
    .end local p3    # "clazz":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
    :goto_0
    throw v5

    .line 231
    .end local v3    # "httpError":Lcom/virgilsecurity/sdk/common/HttpError;
    .end local v4    # "in":Ljava/io/InputStream;
    .restart local v1    # "body":Ljava/lang/String;
    .restart local p1    # "urlConnection":Ljava/net/HttpURLConnection;
    .restart local p2    # "requestBody":Ljava/lang/Object;
    .restart local p3    # "clazz":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
    :cond_2
    sget-object v2, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;->LOGGER:Ljava/util/logging/Logger;

    const-string v3, "Extracting response body..."

    invoke-virtual {v2, v3}, Ljava/util/logging/Logger;->fine(Ljava/lang/String;)V

    .line 232
    new-instance v3, Ljava/io/BufferedInputStream;

    invoke-virtual {p1}, Ljava/net/HttpURLConnection;->getInputStream()Ljava/io/InputStream;

    move-result-object v4

    invoke-direct {v3, v4}, Ljava/io/BufferedInputStream;-><init>(Ljava/io/InputStream;)V
    :try_end_4
    .catchall {:try_start_4 .. :try_end_4} :catchall_6

    .line 233
    .local v3, "instream":Ljava/io/InputStream;
    :try_start_5
    invoke-static {v3}, Lcom/virgilsecurity/sdk/utils/ConvertionUtils;->toString(Ljava/io/InputStream;)Ljava/lang/String;

    move-result-object v4

    .line 234
    .local v4, "responseBody":Ljava/lang/String;
    invoke-static {}, Lcom/virgilsecurity/sdk/utils/ConvertionUtils;->getGson()Lcom/google/gson/Gson;

    move-result-object v5

    invoke-virtual {v5, v4, p3}, Lcom/google/gson/Gson;->fromJson(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;

    move-result-object v5
    :try_end_5
    .catchall {:try_start_5 .. :try_end_5} :catchall_3

    .line 235
    .local v5, "response":Ljava/lang/Object;, "TT;"
    nop

    .line 236
    :try_start_6
    invoke-virtual {v3}, Ljava/io/InputStream;->close()V
    :try_end_6
    .catchall {:try_start_6 .. :try_end_6} :catchall_6

    .line 239
    invoke-virtual {v2, v0}, Ljava/util/logging/Logger;->fine(Ljava/lang/String;)V

    .line 240
    invoke-virtual {p1}, Ljava/net/HttpURLConnection;->disconnect()V

    .line 235
    return-object v5

    .line 232
    .end local v4    # "responseBody":Ljava/lang/String;
    .end local v5    # "response":Ljava/lang/Object;, "TT;"
    :catchall_3
    move-exception v2

    .end local v1    # "body":Ljava/lang/String;
    .end local v3    # "instream":Ljava/io/InputStream;
    .end local p1    # "urlConnection":Ljava/net/HttpURLConnection;
    .end local p2    # "requestBody":Ljava/lang/Object;
    .end local p3    # "clazz":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
    :try_start_7
    throw v2
    :try_end_7
    .catchall {:try_start_7 .. :try_end_7} :catchall_4

    .line 236
    .restart local v1    # "body":Ljava/lang/String;
    .restart local v3    # "instream":Ljava/io/InputStream;
    .restart local p1    # "urlConnection":Ljava/net/HttpURLConnection;
    .restart local p2    # "requestBody":Ljava/lang/Object;
    .restart local p3    # "clazz":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
    :catchall_4
    move-exception v4

    :try_start_8
    invoke-virtual {v3}, Ljava/io/InputStream;->close()V
    :try_end_8
    .catchall {:try_start_8 .. :try_end_8} :catchall_5

    goto :goto_1

    :catchall_5
    move-exception v5

    :try_start_9
    invoke-virtual {v2, v5}, Ljava/lang/Throwable;->addSuppressed(Ljava/lang/Throwable;)V

    .end local v1    # "body":Ljava/lang/String;
    .end local p1    # "urlConnection":Ljava/net/HttpURLConnection;
    .end local p2    # "requestBody":Ljava/lang/Object;
    .end local p3    # "clazz":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
    :goto_1
    throw v4
    :try_end_9
    .catchall {:try_start_9 .. :try_end_9} :catchall_6

    .line 239
    .end local v3    # "instream":Ljava/io/InputStream;
    .restart local v1    # "body":Ljava/lang/String;
    .restart local p1    # "urlConnection":Ljava/net/HttpURLConnection;
    .restart local p2    # "requestBody":Ljava/lang/Object;
    .restart local p3    # "clazz":Ljava/lang/Class;, "Ljava/lang/Class<TT;>;"
    :catchall_6
    move-exception v2

    sget-object v3, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;->LOGGER:Ljava/util/logging/Logger;

    invoke-virtual {v3, v0}, Ljava/util/logging/Logger;->fine(Ljava/lang/String;)V

    .line 240
    invoke-virtual {p1}, Ljava/net/HttpURLConnection;->disconnect()V

    .line 241
    throw v2
.end method


# virtual methods
.method public generateSeed([BLjava/lang/String;Ljava/lang/String;)[B
    .locals 5
    .param p1, "blindedPassword"    # [B
    .param p2, "brainKeyId"    # Ljava/lang/String;
    .param p3, "token"    # Ljava/lang/String;
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Lcom/virgilsecurity/pythia/model/exception/VirgilPythiaServiceException;
        }
    .end annotation

    .line 159
    new-instance v0, Lcom/virgilsecurity/pythia/model/request/GenerateSeedRequest;

    invoke-direct {v0, p1, p2}, Lcom/virgilsecurity/pythia/model/request/GenerateSeedRequest;-><init>([BLjava/lang/String;)V

    .line 162
    .local v0, "request":Lcom/virgilsecurity/pythia/model/request/GenerateSeedRequest;
    :try_start_0
    const-string v1, "pythia/v1/brainkey"

    invoke-direct {p0, v1, p3}, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;->createConnection(Ljava/lang/String;Ljava/lang/String;)Ljava/net/HttpURLConnection;

    move-result-object v1

    .line 163
    .local v1, "urlConnection":Ljava/net/HttpURLConnection;
    const-string/jumbo v2, "virgil-agent"

    iget-object v3, p0, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;->brainkeyVirgilAgent:Ljava/lang/String;

    invoke-virtual {v1, v2, v3}, Ljava/net/HttpURLConnection;->setRequestProperty(Ljava/lang/String;Ljava/lang/String;)V

    .line 164
    const-class v2, Lcom/virgilsecurity/pythia/model/GenerateSeedResponse;

    invoke-direct {p0, v1, v0, v2}, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;->execute(Ljava/net/HttpURLConnection;Ljava/lang/Object;Ljava/lang/Class;)Ljava/lang/Object;

    move-result-object v2

    check-cast v2, Lcom/virgilsecurity/pythia/model/GenerateSeedResponse;

    invoke-virtual {v2}, Lcom/virgilsecurity/pythia/model/GenerateSeedResponse;->getSeed()[B

    move-result-object v2
    :try_end_0
    .catch Lcom/virgilsecurity/pythia/model/exception/VirgilPythiaServiceException; {:try_start_0 .. :try_end_0} :catch_1
    .catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_0

    return-object v2

    .line 168
    .end local v1    # "urlConnection":Ljava/net/HttpURLConnection;
    :catch_0
    move-exception v1

    .line 169
    .local v1, "e":Ljava/lang/Exception;
    sget-object v2, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;->LOGGER:Ljava/util/logging/Logger;

    sget-object v3, Ljava/util/logging/Level;->SEVERE:Ljava/util/logging/Level;

    const-string v4, "Some service issue occurred during request executing"

    invoke-virtual {v2, v3, v4, v1}, Ljava/util/logging/Logger;->log(Ljava/util/logging/Level;Ljava/lang/String;Ljava/lang/Throwable;)V

    .line 170
    new-instance v2, Lcom/virgilsecurity/pythia/model/exception/VirgilPythiaServiceException;

    const-string v3, "VirgilPythiaClient -> generateSeed was not successful"

    invoke-direct {v2, v3, v1}, Lcom/virgilsecurity/pythia/model/exception/VirgilPythiaServiceException;-><init>(Ljava/lang/String;Ljava/lang/Throwable;)V

    throw v2

    .line 165
    .end local v1    # "e":Ljava/lang/Exception;
    :catch_1
    move-exception v1

    .line 166
    .local v1, "e":Lcom/virgilsecurity/pythia/model/exception/VirgilPythiaServiceException;
    sget-object v2, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;->LOGGER:Ljava/util/logging/Logger;

    sget-object v3, Ljava/util/logging/Level;->SEVERE:Ljava/util/logging/Level;

    const-string v4, "Pythia service returned an error"

    invoke-virtual {v2, v3, v4, v1}, Ljava/util/logging/Logger;->log(Ljava/util/logging/Level;Ljava/lang/String;Ljava/lang/Throwable;)V

    .line 167
    throw v1
.end method

.method public transformPassword([B[BLjava/lang/Integer;ZLjava/lang/String;)Lcom/virgilsecurity/pythia/model/TransformResponse;
    .locals 5
    .param p1, "salt"    # [B
    .param p2, "blindedPassword"    # [B
    .param p3, "version"    # Ljava/lang/Integer;
    .param p4, "includeProof"    # Z
    .param p5, "token"    # Ljava/lang/String;
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Lcom/virgilsecurity/pythia/model/exception/VirgilPythiaServiceException;
        }
    .end annotation

    .line 133
    new-instance v0, Lcom/virgilsecurity/pythia/model/request/TransformPasswordRequest;

    invoke-virtual {p3}, Ljava/lang/Integer;->intValue()I

    move-result v1

    invoke-direct {v0, p1, p2, v1, p4}, Lcom/virgilsecurity/pythia/model/request/TransformPasswordRequest;-><init>([B[BIZ)V

    .line 137
    .local v0, "request":Lcom/virgilsecurity/pythia/model/request/TransformPasswordRequest;
    :try_start_0
    const-string v1, "/pythia/v1/password"

    invoke-direct {p0, v1, p5}, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;->createConnection(Ljava/lang/String;Ljava/lang/String;)Ljava/net/HttpURLConnection;

    move-result-object v1

    .line 138
    .local v1, "urlConnection":Ljava/net/HttpURLConnection;
    const-string/jumbo v2, "virgil-agent"

    iget-object v3, p0, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;->bppVirgilAgent:Ljava/lang/String;

    invoke-virtual {v1, v2, v3}, Ljava/net/HttpURLConnection;->setRequestProperty(Ljava/lang/String;Ljava/lang/String;)V

    .line 139
    const-class v2, Lcom/virgilsecurity/pythia/model/TransformResponse;

    invoke-direct {p0, v1, v0, v2}, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;->execute(Ljava/net/HttpURLConnection;Ljava/lang/Object;Ljava/lang/Class;)Ljava/lang/Object;

    move-result-object v2

    check-cast v2, Lcom/virgilsecurity/pythia/model/TransformResponse;
    :try_end_0
    .catch Lcom/virgilsecurity/pythia/model/exception/VirgilPythiaServiceException; {:try_start_0 .. :try_end_0} :catch_1
    .catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_0

    return-object v2

    .line 143
    .end local v1    # "urlConnection":Ljava/net/HttpURLConnection;
    :catch_0
    move-exception v1

    .line 144
    .local v1, "e":Ljava/lang/Exception;
    sget-object v2, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;->LOGGER:Ljava/util/logging/Logger;

    sget-object v3, Ljava/util/logging/Level;->SEVERE:Ljava/util/logging/Level;

    const-string v4, "Some service issue occurred during request executing"

    invoke-virtual {v2, v3, v4, v1}, Ljava/util/logging/Logger;->log(Ljava/util/logging/Level;Ljava/lang/String;Ljava/lang/Throwable;)V

    .line 145
    new-instance v2, Lcom/virgilsecurity/pythia/model/exception/VirgilPythiaServiceException;

    const-string v3, "VirgilPythiaClient -> transformPassword was not successful"

    invoke-direct {v2, v3, v1}, Lcom/virgilsecurity/pythia/model/exception/VirgilPythiaServiceException;-><init>(Ljava/lang/String;Ljava/lang/Throwable;)V

    throw v2

    .line 140
    .end local v1    # "e":Ljava/lang/Exception;
    :catch_1
    move-exception v1

    .line 141
    .local v1, "e":Lcom/virgilsecurity/pythia/model/exception/VirgilPythiaServiceException;
    sget-object v2, Lcom/virgilsecurity/pythia/client/VirgilPythiaClient;->LOGGER:Ljava/util/logging/Logger;

    sget-object v3, Ljava/util/logging/Level;->SEVERE:Ljava/util/logging/Level;

    const-string v4, "Pythia service returned an error"

    invoke-virtual {v2, v3, v4, v1}, Ljava/util/logging/Logger;->log(Ljava/util/logging/Level;Ljava/lang/String;Ljava/lang/Throwable;)V

    .line 142
    throw v1
.end method
