.class final Lrx/Completable$13;
.super Ljava/lang/Object;
.source "Completable.java"

# interfaces
.implements Lrx/Completable$OnSubscribe;


# annotations
.annotation system Ldalvik/annotation/EnclosingMethod;
    value = Lrx/Completable;->using(Lrx/functions/Func0;Lrx/functions/Func1;Lrx/functions/Action1;Z)Lrx/Completable;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x8
    name = null
.end annotation


# instance fields
.field final synthetic val$completableFunc1:Lrx/functions/Func1;

.field final synthetic val$disposer:Lrx/functions/Action1;

.field final synthetic val$eager:Z

.field final synthetic val$resourceFunc0:Lrx/functions/Func0;


# direct methods
.method constructor <init>(Lrx/functions/Func0;Lrx/functions/Func1;Lrx/functions/Action1;Z)V
    .locals 0

    .line 877
    iput-object p1, p0, Lrx/Completable$13;->val$resourceFunc0:Lrx/functions/Func0;

    iput-object p2, p0, Lrx/Completable$13;->val$completableFunc1:Lrx/functions/Func1;

    iput-object p3, p0, Lrx/Completable$13;->val$disposer:Lrx/functions/Action1;

    iput-boolean p4, p0, Lrx/Completable$13;->val$eager:Z

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method


# virtual methods
.method public bridge synthetic call(Ljava/lang/Object;)V
    .locals 1
    .param p1, "x0"    # Ljava/lang/Object;

    .line 877
    move-object v0, p1

    check-cast v0, Lrx/CompletableSubscriber;

    invoke-virtual {p0, v0}, Lrx/Completable$13;->call(Lrx/CompletableSubscriber;)V

    return-void
.end method

.method public call(Lrx/CompletableSubscriber;)V
    .locals 9
    .param p1, "s"    # Lrx/CompletableSubscriber;

    const-string v0, "The completable supplied is null"

    .line 883
    const/4 v1, 0x0

    :try_start_0
    iget-object v2, p0, Lrx/Completable$13;->val$resourceFunc0:Lrx/functions/Func0;

    invoke-interface {v2}, Lrx/functions/Func0;->call()Ljava/lang/Object;

    move-result-object v2
    :try_end_0
    .catchall {:try_start_0 .. :try_end_0} :catchall_3

    .line 888
    .local v2, "resource":Ljava/lang/Object;, "TR;"
    nop

    .line 893
    const/4 v3, 0x1

    const/4 v4, 0x0

    const/4 v5, 0x2

    :try_start_1
    iget-object v6, p0, Lrx/Completable$13;->val$completableFunc1:Lrx/functions/Func1;

    invoke-interface {v6, v2}, Lrx/functions/Func1;->call(Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v6

    check-cast v6, Lrx/Completable;
    :try_end_1
    .catchall {:try_start_1 .. :try_end_1} :catchall_1

    move-object v1, v6

    .line 910
    .local v1, "cs":Lrx/Completable;
    nop

    .line 912
    if-nez v1, :cond_0

    .line 914
    :try_start_2
    iget-object v6, p0, Lrx/Completable$13;->val$disposer:Lrx/functions/Action1;

    invoke-interface {v6, v2}, Lrx/functions/Action1;->call(Ljava/lang/Object;)V
    :try_end_2
    .catchall {:try_start_2 .. :try_end_2} :catchall_0

    .line 921
    nop

    .line 922
    invoke-static {}, Lrx/subscriptions/Subscriptions;->unsubscribed()Lrx/Subscription;

    move-result-object v3

    invoke-interface {p1, v3}, Lrx/CompletableSubscriber;->onSubscribe(Lrx/Subscription;)V

    .line 923
    new-instance v3, Ljava/lang/NullPointerException;

    invoke-direct {v3, v0}, Ljava/lang/NullPointerException;-><init>(Ljava/lang/String;)V

    invoke-interface {p1, v3}, Lrx/CompletableSubscriber;->onError(Ljava/lang/Throwable;)V

    .line 924
    return-void

    .line 915
    :catchall_0
    move-exception v6

    .line 916
    .local v6, "ex":Ljava/lang/Throwable;
    invoke-static {v6}, Lrx/exceptions/Exceptions;->throwIfFatal(Ljava/lang/Throwable;)V

    .line 918
    invoke-static {}, Lrx/subscriptions/Subscriptions;->unsubscribed()Lrx/Subscription;

    move-result-object v7

    invoke-interface {p1, v7}, Lrx/CompletableSubscriber;->onSubscribe(Lrx/Subscription;)V

    .line 919
    new-instance v7, Lrx/exceptions/CompositeException;

    new-array v5, v5, [Ljava/lang/Throwable;

    new-instance v8, Ljava/lang/NullPointerException;

    invoke-direct {v8, v0}, Ljava/lang/NullPointerException;-><init>(Ljava/lang/String;)V

    aput-object v8, v5, v4

    aput-object v6, v5, v3

    invoke-static {v5}, Ljava/util/Arrays;->asList([Ljava/lang/Object;)Ljava/util/List;

    move-result-object v0

    invoke-direct {v7, v0}, Lrx/exceptions/CompositeException;-><init>(Ljava/util/Collection;)V

    invoke-interface {p1, v7}, Lrx/CompletableSubscriber;->onError(Ljava/lang/Throwable;)V

    .line 920
    return-void

    .line 927
    .end local v6    # "ex":Ljava/lang/Throwable;
    :cond_0
    new-instance v0, Ljava/util/concurrent/atomic/AtomicBoolean;

    invoke-direct {v0}, Ljava/util/concurrent/atomic/AtomicBoolean;-><init>()V

    .line 929
    .local v0, "once":Ljava/util/concurrent/atomic/AtomicBoolean;
    new-instance v3, Lrx/Completable$13$1;

    invoke-direct {v3, p0, v0, v2, p1}, Lrx/Completable$13$1;-><init>(Lrx/Completable$13;Ljava/util/concurrent/atomic/AtomicBoolean;Ljava/lang/Object;Lrx/CompletableSubscriber;)V

    invoke-virtual {v1, v3}, Lrx/Completable;->unsafeSubscribe(Lrx/CompletableSubscriber;)V

    .line 992
    return-void

    .line 894
    .end local v0    # "once":Ljava/util/concurrent/atomic/AtomicBoolean;
    .end local v1    # "cs":Lrx/Completable;
    :catchall_1
    move-exception v0

    .line 896
    .local v0, "e":Ljava/lang/Throwable;
    .restart local v1    # "cs":Lrx/Completable;
    :try_start_3
    iget-object v6, p0, Lrx/Completable$13;->val$disposer:Lrx/functions/Action1;

    invoke-interface {v6, v2}, Lrx/functions/Action1;->call(Ljava/lang/Object;)V
    :try_end_3
    .catchall {:try_start_3 .. :try_end_3} :catchall_2

    .line 904
    nop

    .line 905
    invoke-static {v0}, Lrx/exceptions/Exceptions;->throwIfFatal(Ljava/lang/Throwable;)V

    .line 907
    invoke-static {}, Lrx/subscriptions/Subscriptions;->unsubscribed()Lrx/Subscription;

    move-result-object v3

    invoke-interface {p1, v3}, Lrx/CompletableSubscriber;->onSubscribe(Lrx/Subscription;)V

    .line 908
    invoke-interface {p1, v0}, Lrx/CompletableSubscriber;->onError(Ljava/lang/Throwable;)V

    .line 909
    return-void

    .line 897
    :catchall_2
    move-exception v6

    .line 898
    .restart local v6    # "ex":Ljava/lang/Throwable;
    invoke-static {v0}, Lrx/exceptions/Exceptions;->throwIfFatal(Ljava/lang/Throwable;)V

    .line 899
    invoke-static {v6}, Lrx/exceptions/Exceptions;->throwIfFatal(Ljava/lang/Throwable;)V

    .line 901
    invoke-static {}, Lrx/subscriptions/Subscriptions;->unsubscribed()Lrx/Subscription;

    move-result-object v7

    invoke-interface {p1, v7}, Lrx/CompletableSubscriber;->onSubscribe(Lrx/Subscription;)V

    .line 902
    new-instance v7, Lrx/exceptions/CompositeException;

    new-array v5, v5, [Ljava/lang/Throwable;

    aput-object v0, v5, v4

    aput-object v6, v5, v3

    invoke-static {v5}, Ljava/util/Arrays;->asList([Ljava/lang/Object;)Ljava/util/List;

    move-result-object v3

    invoke-direct {v7, v3}, Lrx/exceptions/CompositeException;-><init>(Ljava/util/Collection;)V

    invoke-interface {p1, v7}, Lrx/CompletableSubscriber;->onError(Ljava/lang/Throwable;)V

    .line 903
    return-void

    .line 884
    .end local v0    # "e":Ljava/lang/Throwable;
    .end local v1    # "cs":Lrx/Completable;
    .end local v2    # "resource":Ljava/lang/Object;, "TR;"
    .end local v6    # "ex":Ljava/lang/Throwable;
    :catchall_3
    move-exception v0

    .line 885
    .restart local v0    # "e":Ljava/lang/Throwable;
    .local v1, "resource":Ljava/lang/Object;, "TR;"
    invoke-static {}, Lrx/subscriptions/Subscriptions;->unsubscribed()Lrx/Subscription;

    move-result-object v2

    invoke-interface {p1, v2}, Lrx/CompletableSubscriber;->onSubscribe(Lrx/Subscription;)V

    .line 886
    invoke-interface {p1, v0}, Lrx/CompletableSubscriber;->onError(Ljava/lang/Throwable;)V

    .line 887
    return-void
.end method
