.class public Lfreemarker/debug/DebuggerClient;
.super Ljava/lang/Object;
.source "DebuggerClient.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lfreemarker/debug/DebuggerClient$LocalDebuggerProxy;
    }
.end annotation


# direct methods
.method private constructor <init>()V
    .locals 0

    .line 40
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 41
    return-void
.end method

.method public static getDebugger(Ljava/net/InetAddress;ILjava/lang/String;)Lfreemarker/debug/Debugger;
    .locals 8
    .param p0, "host"    # Ljava/net/InetAddress;
    .param p1, "port"    # I
    .param p2, "password"    # Ljava/lang/String;
    .annotation system Ldalvik/annotation/Throws;
        value = {
            Ljava/io/IOException;
        }
    .end annotation

    .line 65
    :try_start_0
    new-instance v0, Ljava/net/Socket;

    invoke-direct {v0, p0, p1}, Ljava/net/Socket;-><init>(Ljava/net/InetAddress;I)V
    :try_end_0
    .catch Ljava/io/IOException; {:try_start_0 .. :try_end_0} :catch_1
    .catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_0

    .line 68
    .local v0, "s":Ljava/net/Socket;
    :try_start_1
    new-instance v1, Ljava/io/ObjectOutputStream;

    invoke-virtual {v0}, Ljava/net/Socket;->getOutputStream()Ljava/io/OutputStream;

    move-result-object v2

    invoke-direct {v1, v2}, Ljava/io/ObjectOutputStream;-><init>(Ljava/io/OutputStream;)V

    .line 69
    .local v1, "out":Ljava/io/ObjectOutputStream;
    new-instance v2, Ljava/io/ObjectInputStream;

    invoke-virtual {v0}, Ljava/net/Socket;->getInputStream()Ljava/io/InputStream;

    move-result-object v3

    invoke-direct {v2, v3}, Ljava/io/ObjectInputStream;-><init>(Ljava/io/InputStream;)V

    .line 70
    .local v2, "in":Ljava/io/ObjectInputStream;
    invoke-virtual {v2}, Ljava/io/ObjectInputStream;->readInt()I

    move-result v3

    .line 71
    .local v3, "protocolVersion":I
    const/16 v4, 0xdc

    if-gt v3, v4, :cond_0

    .line 77
    invoke-virtual {v2}, Ljava/io/ObjectInputStream;->readObject()Ljava/lang/Object;

    move-result-object v4

    check-cast v4, [B

    check-cast v4, [B

    .line 78
    .local v4, "challenge":[B
    const-string v5, "SHA"

    invoke-static {v5}, Ljava/security/MessageDigest;->getInstance(Ljava/lang/String;)Ljava/security/MessageDigest;

    move-result-object v5

    .line 79
    .local v5, "md":Ljava/security/MessageDigest;
    const-string v6, "UTF-8"

    invoke-virtual {p2, v6}, Ljava/lang/String;->getBytes(Ljava/lang/String;)[B

    move-result-object v6

    invoke-virtual {v5, v6}, Ljava/security/MessageDigest;->update([B)V

    .line 80
    invoke-virtual {v5, v4}, Ljava/security/MessageDigest;->update([B)V

    .line 81
    invoke-virtual {v5}, Ljava/security/MessageDigest;->digest()[B

    move-result-object v6

    invoke-virtual {v1, v6}, Ljava/io/ObjectOutputStream;->writeObject(Ljava/lang/Object;)V

    .line 82
    new-instance v6, Lfreemarker/debug/DebuggerClient$LocalDebuggerProxy;

    invoke-virtual {v2}, Ljava/io/ObjectInputStream;->readObject()Ljava/lang/Object;

    move-result-object v7

    check-cast v7, Lfreemarker/debug/Debugger;

    invoke-direct {v6, v7}, Lfreemarker/debug/DebuggerClient$LocalDebuggerProxy;-><init>(Lfreemarker/debug/Debugger;)V
    :try_end_1
    .catchall {:try_start_1 .. :try_end_1} :catchall_0

    .line 87
    :try_start_2
    invoke-virtual {v0}, Ljava/net/Socket;->close()V
    :try_end_2
    .catch Ljava/io/IOException; {:try_start_2 .. :try_end_2} :catch_1
    .catch Ljava/lang/Exception; {:try_start_2 .. :try_end_2} :catch_0

    return-object v6

    .line 73
    .end local v4    # "challenge":[B
    .end local v5    # "md":Ljava/security/MessageDigest;
    :cond_0
    :try_start_3
    new-instance v4, Ljava/io/IOException;

    new-instance v5, Ljava/lang/StringBuffer;

    invoke-direct {v5}, Ljava/lang/StringBuffer;-><init>()V

    const-string v6, "Incompatible protocol version "

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5, v3}, Ljava/lang/StringBuffer;->append(I)Ljava/lang/StringBuffer;

    move-result-object v5

    const-string v6, ". At most 220 was expected."

    invoke-virtual {v5, v6}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;

    move-result-object v5

    invoke-virtual {v5}, Ljava/lang/StringBuffer;->toString()Ljava/lang/String;

    move-result-object v5

    invoke-direct {v4, v5}, Ljava/io/IOException;-><init>(Ljava/lang/String;)V

    .end local v0    # "s":Ljava/net/Socket;
    .end local p0    # "host":Ljava/net/InetAddress;
    .end local p1    # "port":I
    .end local p2    # "password":Ljava/lang/String;
    throw v4
    :try_end_3
    .catchall {:try_start_3 .. :try_end_3} :catchall_0

    .line 87
    .end local v1    # "out":Ljava/io/ObjectOutputStream;
    .end local v2    # "in":Ljava/io/ObjectInputStream;
    .end local v3    # "protocolVersion":I
    .restart local v0    # "s":Ljava/net/Socket;
    .restart local p0    # "host":Ljava/net/InetAddress;
    .restart local p1    # "port":I
    .restart local p2    # "password":Ljava/lang/String;
    :catchall_0
    move-exception v1

    :try_start_4
    invoke-virtual {v0}, Ljava/net/Socket;->close()V

    .end local p0    # "host":Ljava/net/InetAddress;
    .end local p1    # "port":I
    .end local p2    # "password":Ljava/lang/String;
    throw v1
    :try_end_4
    .catch Ljava/io/IOException; {:try_start_4 .. :try_end_4} :catch_1
    .catch Ljava/lang/Exception; {:try_start_4 .. :try_end_4} :catch_0

    .line 94
    .end local v0    # "s":Ljava/net/Socket;
    .restart local p0    # "host":Ljava/net/InetAddress;
    .restart local p1    # "port":I
    .restart local p2    # "password":Ljava/lang/String;
    :catch_0
    move-exception v0

    .line 96
    .local v0, "e":Ljava/lang/Exception;
    new-instance v1, Lfreemarker/template/utility/UndeclaredThrowableException;

    invoke-direct {v1, v0}, Lfreemarker/template/utility/UndeclaredThrowableException;-><init>(Ljava/lang/Throwable;)V

    throw v1

    .line 90
    .end local v0    # "e":Ljava/lang/Exception;
    :catch_1
    move-exception v0

    .line 92
    .local v0, "e":Ljava/io/IOException;
    throw v0
.end method
